apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: stress-test-memez
spec:
  description: Run stress Tests
  workspaces:
    - name: output
  params:
    - name: api-url
      description: The URL of the API to test
      type: string
  steps:
    - name: run-stress-tests
      image: grafana/k6:latest
      workingDir: /workspace/output
      script: |
        #!/bin/sh
        make test-stress
    - name: verify-stress-reports
      workingDir: /workspace/output
      image: alpine
      script: |
        #!/bin/sh
        ls -R out
    - name: publish-results
      workingDir: /workspace/output
      image: alpine
      script: |
        #!/bin/sh
        echo "Send stress test results somewhere, like SonarQube.."